name: C/C++ CI

on:
  push:
    branches:
      - main
      - release/*

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            compiler: gcc
          - os: ubuntu-latest
            compiler: clang
          - os: windows-latest
            compiler: vs2019
          - os: macos-latest
            compiler: clang

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: alisyyed/tinygltf
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh-strict: true
          persist-credentials: true
          clean: true
          fetch-depth: 1
          lfs: false
          submodules: false
          set-safe-directory: true

      - name: Configure Git
        run: git config --global --add safe.directory ${{ github.workspace }}/tinygltf

      - name: Install build essentials
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt-get update
            sudo apt-get install -y build-essential
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            choco install visualstudio2019buildtools --package-parameters "--includeRecommended --includeOptional"
          fi

      - name: Set up CMake ${{ matrix.compiler }}
        uses: dawidd6/action-cmake@v1
        with:
          cmake-version: 3.21

      - name: Build and Test
        run: |
          cd ${{ github.workspace }}/tinygltf
          mkdir build
          cd build
          cmake ..
          cmake --build .
          ctest
