name: C/C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache
          key: ${{ runner.os }}-build-${{ hashFiles('**/CMakeLists.txt') }}

      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

          # Perform your build steps here
          # For example:
          - name: Build with MinGW gcc cross
            if: matrix.os == 'ubuntu-latest'
            run: |
              sudo apt-get install -y mingw-w64
              x86_64-w64-mingw32-g++ -std=c++11 -o loader_example loader_example.cc

          - name: Build for Windows(x64, MSVC)
            if: matrix.os == 'windows-latest'
            run: |
              mkdir build
              cd build
              cmake -G "Visual Studio 17 2022" -A x64 -DTINYGLTF_BUILD_LOADER_EXAMPLE=On -DTINYGLTF_BUILD_GL_EXAMPLES=Off -DTINYGLTF_BUILD_VALIDATOR_EXAMPLE=On ..
              cmake --build . --config Release
              cd ..

          - name: Buld with gcc
            if: matrix.os == 'ubuntu-latest'
            run: |
              g++ -std=c++11 -o loader_example loader_example.cc

          - name: Buld with gcc + rapidjson
            if: matrix.os == 'ubuntu-latest'
            run: |
              git clone https://github.com/Tencent/rapidjson
              g++ -DTINYGLTF_USE_RAPIDJSON -I./rapidjson/include/rapidjson -std=c++11 -o loader_example loader_example.cc

          - name: Build on cross aarch64
            if: matrix.os == 'ubuntu-latest'
            run: |
              sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
              git clone https://github.com/Tencent/rapidjson
              aarch64-linux-gnu-g++ -DTINYGLTF_USE_RAPIDJSON -I./rapidjson/include/rapidjson -std=c++11 -g -O0 -o loader_example loader_example.cc

          - name: Build on macOS
            if: matrix.os == 'macos-latest'
            run: |
              clang++ -std=c++11 -g -O0 -o loader_example loader_example.cc
              ./loader_example models/Cube/Cube.gltf
              git clone https://github.com/Tencent/rapidjson
              clang++ -DTINYGLTF_USE_RAPIDJSON -I./rapidjson/include/rapidjson -std=c++11 -g -O0 -o loader_example loader_example.cc

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: build-artifact
          path: |
            loader_example
