name: C/C++ CI

on:
  push:
    branches:
      - main
      - release/*

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            compiler: gcc
          - os: ubuntu-latest
            compiler: clang

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: alisyyed/tinygltf
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh-strict: true
          persist-credentials: true
          clean: true
          fetch-depth: 1
          lfs: false
          submodules: false
          set-safe-directory: true

      - name: Configure Git
        run: |
          git config --global --add safe.directory ${{ github.workspace }}/tinygltf

      - name: Set up CMake ${{ matrix.compiler }}
        uses: dawidd6/action-cmake@v1
        with:
          cmake-version: 3.21

      - name: Build and Test
        run: |
          cd ${{ github.workspace }}/tinygltf
          mkdir build
          cd build
          cmake ..
          make
          make test
